### ISSUE TITLE
Q; in the resulting Decision Tree example: ...

### ISSUE THREAD

**Issue by sfd99** [TheLondonPeacock/SeaClass#2]
**Hi Chris and Seagate Team,**

**SeaClass:** _Really nice R PKG!_ 
THANKS!

Following the simple "**rareFailData** "example.

**Q:**
_at each split node_
of  the resulting **Decision Tree**,
(where there is condition, ie:  X14 < -1.84) 
is the branch to the left of this condition TRUE or FALSE?.

Same question _for all other branches_:
which is the **True** branch and which is the **False** branch 
at each "test condition" split node?

_Thks!_
**SFd99
San Francisco**
**Rstudio
Linux Ubuntu 14.04 32-bit
Pale Moon browser**

**Comment by ChrisDienes** [comment]
The decision tree module uses the `rpart` package. When using the `plot` function to display the fitted tree, left splits correspond to TRUE and right splits correspond to FALSE. Yes this isn't obvious, and maybe a different plotting tool should be used for clarity. Thanks for pointing this out.
