### ISSUE TITLE
Error "The variable selected is not binary", when it really is binary

### ISSUE THREAD

**Issue by dkaufman-c7ks7s** [TheLondonPeacock/SeaClass#3]
SeaClass is working correctly on the rareFailData example in my installation.

However, I get the error message "The variable selected is not binary" puzzlingly when I try on my own data set.  

In the SeaClass GUI, I point to my existing data frame `qqq` (1000 observations, 27 variables) and I identify its column `mx_occur_w_pseudo` as the response variable, and SeaClass immediately returns the error message.  When I attempt to diagnose:
```
typeof(qqq$mx_occur_w_pseudo)
[1] "integer"
> class(qqq$mx_occur_w_pseudo)
[1] "integer"
> table(qqq$mx_occur_w_pseudo)

  0   1 
703 297 
> length(unique(qqq$mx_occur_w_pseudo))
[1] 2

```
I did that final length command because it's in the actual test at lines 210-212 of SeaClass.R.  It comes out to 2, so how am I falling into the error text case?

P.S.  FWIW, changing qqq$mx_occur_w_pseudo has no effect (except the class() result is "factor").

**Comment by dkaufman-c7ks7s** [comment]
Reproducible example:

```
qqq <- structure(list(location_short = c("3013", "3013", "3013", "3013"), 
                      mx_occur_w_pseudo = c(1L, 0L, 0L, 0L), 
                      Severity_new = c(-100, 1, -100, -100), 
                      rating_new = c(-100, 2, -100, -100)), 
                 row.names = c(NA, -4L), 
                 .Names = c("location_short", "mx_occur_w_pseudo", "Severity_new", "rating_new"), 
                 class = c("tbl_df", "tbl", "data.frame"))
table(qqq$mx_occur_w_pseudo)
length(unique(qqq$mx_occur_w_pseudo))

```
Try it in SeaClass with `mx_occur_w_pseudo` as the response variable (or `Severity_new`, or `rating_new`) and the error occurs.

**Comment by ChrisDienes** [comment]
Thank you for the reproducible example! Let me know if this fixes your problem for your version of SeaClass:

The problem lies with the class specification. My application doesn't appear to be friends with the classes `tbl` and `tbl_df` (http://tibble.tidyverse.org/).
Here are two fixes for your SeaClass version:
1. Modify your structure from `class = c("tbl_df", "tbl", "data.frame")` to `class = "data.frame"`
2. Use your current structure, then run `qqq <- as.data.frame(qqq)` prior to launching the application. See here also: https://stackoverflow.com/questions/37594411/convert-classes-tbl-df-tbl-and-data-frame-into-dataframe-with-r

For details see:
```
qqq <- structure(list(location_short = c("3013", "3013", "3013", "3013"), 
                      mx_occur_w_pseudo = c(1L, 0L, 0L, 0L), 
                      Severity_new = c(-100, 1, -100, -100), 
                      rating_new = c(-100, 2, -100, -100)), 
                 row.names = c(NA, -4L), 
                 .Names = c("location_short", "mx_occur_w_pseudo", "Severity_new", "rating_new"), 
                 class = c("tbl_df", "tbl", "data.frame"))
                 #class = "data.frame")
table(qqq$mx_occur_w_pseudo)
length(unique(qqq$mx_occur_w_pseudo))
class(qqq)
my_cases = qqq[,"mx_occur_w_pseudo"]
length(unique(my_cases))
qqq <- as.data.frame(qqq)
class(qqq)
my_cases = qqq[,"mx_occur_w_pseudo"]
length(unique(qqq$mx_occur_w_pseudo))
```

**Comment by dkaufman-c7ks7s** [comment]
That works, thanks.  Was there a passing mention somewhere in the docs that this could be a problem?  I feel like I may have run across something related this morning when I was bumping around looking for clues, but the significance of it escaped me at the time, and it might have been from a reference that wasn't specific to SeaClass.

**Comment by ChrisDienes** [comment]
I think it's specified that the data set needs to be a data frame, but this is the first time I've encountered your problem with the tbl and tbl_df classes. Thanks for bringing it to my attention.
